exception InvalidUnaryOperation
exception UndefinedId of string
exception InvalidAssignment
exception InvalidArgument
exception InvalidBinaryOperation
exception InvalidListType
exception InvalidPostOperation
exception WrongNumberOfArguments
exception DuplicateVariable of string
exception InvalidAssignmentOperation of string
exception WrongType of string
exception NothingAfterReturn
exception ReturnsOutsideFunction
exception NonListAccess
exception NonListLength
exception NonNumIndex
exception IndexOutOfBounds
exception TestException of string
