import subprocess
import os

# LLI Path
PATH = '/usr/local/opt/llvm@3.8/bin/lli-3.8'

# Helper functions

# Compare two files. Return the number of differing lines.
def compare(f1, f2):
	diff = 0
	for line1 in f1:
		for line2 in f2:
			if line1 != line2:
				diff = diff + 1
			break
	return diff

# MAIN
llvm_out = open("hello_world/hello.ll", "w") # output of codegen (llvm code)
test_out = open("hello_world/hello.out", "w") # output of running the llvm code

subprocess.run(['ocamlbuild', '-use-ocamlfind', '-pkgs', 'llvm,llvm.analysis', '-cflags', '-w,+a-4', 'toplevel.native'],
	stdout=subprocess.PIPE, stderr = subprocess.PIPE)

subprocess.run(['./toplevel.native', '-l', 'hello.joel'], 
	stdout=llvm_out, stderr=subprocess.PIPE)

result = subprocess.run([PATH, 'hello_world/hello.ll'],
	stdout=test_out, stderr=subprocess.PIPE)

llvm_out.close()
test_out.close()

test_out = open("hello_world/hello.out", "r") # open llvm output for reading
gold_standard = open("hello_world/hello.standard", "r") # the "gold standard"

#diff = set(test_out).symmetric_difference(gold_standard) # compare the llvm output to the gold standard
diff = compare(test_out, gold_standard)

# remove files generated by this script
os.remove("hello_world/hello.ll")
os.remove("hello_world/hello.out")
os.remove("toplevel.native")

if diff == 0:
	print("TEST SUITE PASSED")
else:
	print("TEST SUITE FAILED")
	print(diff)

